### ISSUE TITLE
getUserName(self), ha nincs bejeltkezve a felhasználó?

### ISSUE THREAD

**Issue by RobiiHUN** [krusoadi/PEP_V2#1]
A music.py fájlban mi történik a getUserName(self) függvénynél, ha nincs bejelentkezve a felhasználó?
Rakj egy else ágat is, és írd ki hogy nincs bejelentkezve

**Comment by krusoadi** [comment]
Elméletben nem tud eljutni a program oda, ha nem sikerült bejelentkezni. Viszont a bejelentkezésnél felmerülő error javításánál felhasználom már, hiszen tökéletes indikátor arra, hogy sikeres volt e a bejelentkezés. Köszi a kommentet, rávilágított egy olyan bug-ra amit nem teszteltem eléggé, így a bejelentkezést újra lehet próbálni, ha nem volt sikeres.
